/**********************  Phase 2 – Northwind Interview Questions (Round 1) **********************************/
/*
Q1
Display all customers who have placed at least one order.
Output:
CustomerID
CompanyName
OrderID
OrderDate
*/
SELECT c.id AS CustomerID,
       c.company AS CompanyName,
       o.id AS OrderID, 
       o.order_date AS OrderDate
FROM customers c
INNER JOIN orders o
ON c.id = o.customer_id;



/*
Q2
Display all employees who handled orders shipped to Germany.
Output:
EmployeeName
OrderID
ShipCountry
*/
SELECT CONCAT(e.first_name, ' ', e.last_name) AS  EmployeeName,
	   o.id AS OrderID,
       o.ship_country_region AS ShipCountry
FROM employees e 
INNER JOIN orders o 
ON e.id = o.employee_id
WHERE o.ship_country_region = 'Germany';


/*
Q3
Display every product along with its supplier name.
Output:
ProductName
SupplierName
UnitPrice
*/
SELECT s.company AS SupplierName,
       p.product_name AS ProductName,
       p.list_price AS UnitPrice
FROM suppliers s
INNER JOIN products p 
ON p.supplier_ids = s.id;


/*
Q4
Display all products belonging to the Beverages category.
Output:
ProductName
CategoryName
UnitPrice
*/
SELECT product_name AS ProductName,
       category AS CategoryName,
	   list_price AS UnitPrice
FROM products
WHERE category = 'Beverages';


/*
Q5
Display customers from France ordered alphabetically.
Output:
CompanyName
City
Country
*/
SELECT company AS CompanyName,
       city AS City,
       country_region AS Country
FROM customers
WHERE country_region = 'France'
ORDER BY CompanyName ASC;


/*
Q6
Display orders that were shipped after the required date.
Output:
OrderID
RequiredDate
ShippedDate

*/
SELECT id AS OrderId,
       order_date AS RequiredDate,
       shipped_date AS ShippedDate
FROM orders
WHERE order_date < shipped_date;


/*
Q7
Display products costing more than the average product price.
(Hint: Subquery)
*/
SELECT product_name
FROM products
WHERE list_price > (
      SELECT AVG(list_price)
      FROM products
);


/*
Q8
Display customers who never placed an order.
(Hint: LEFT JOIN)
*/
SELECT CONCAT(c.first_name, ' ', c.last_name) AS customer_name
FROM  customers c 
LEFT JOIN orders o
ON c.id = o.customer_id
WHERE o.id IS NULL;

-- Northwind customers are companies.
SELECT
    c.company
FROM customers c
LEFT JOIN orders o
ON c.id=o.customer_id
WHERE o.id IS NULL;

/*
Q9
Display suppliers who supply more than 5 products.
Output
SupplierName
TotalProducts
*/
SELECT CONCAT(s.first_name, s.last_name) AS SupplierName,
       COUNT(p.id) AS TotalProducts
FROM suppliers s
INNER JOIN products p 
ON p.supplier_ids = s.id
GROUP BY s.id, SupplierName
HAVING COUNT(p.id) > 5;

-- CORRECT QUERY
SELECT
    s.company,
    COUNT(p.id) AS TotalProducts
FROM suppliers s
JOIN products p
ON s.id=p.supplier_ids
GROUP BY s.id,s.company
HAVING COUNT(*)>5;

/*
Q10
Display the total revenue generated by each category.
Output
CategoryName
Revenue
*/
SELECT category AS CategoryName,
       SUM(list_price) - SUM(standard_cost) AS Revenue
FROM products
GROUP BY category;


/*
This one is the biggest mistake.
You calculated
SUM(list_price)-SUM(standard_cost)
That is potential profit, not revenue.
Revenue is
Quantity × Unit Price
In Northwind it comes from
order_details

*/

-- CORRECT QUERY
SELECT
    p.category,
    SUM(od.quantity * od.unit_price) AS Revenue
FROM order_details od
JOIN products p
ON od.product_id=p.id
GROUP BY p.category;


SHOW TABLES;

/**************************     Round 2 – GROUP BY + HAVING     ********************************/
/*
Q11
Find customers who placed more than 10 orders.
*/
SELECT c.first_name,
       c.last_name,
       COUNT(o.id) AS total_orders
FROM customers c 
INNER JOIN orders o 
ON c.id = o.customer_id
GROUP BY c.id, c.first_name, c.last_name
HAVING COUNT(o.id) > 10;


/*
Q12
Display employees whose average freight handled exceeds 50.
*/
SELECT e.first_name, 
       e.last_name,
       AVG(o.shipping_fee) AS avg_freight_handled
FROM employees e 
INNER JOIN orders o 
ON e.id = o.employee_id
GROUP BY e.id, e.first_name, e.last_name
HAVING AVG(o.shipping_fee) > 50;

/*
Q13
Display categories having more than 10 products.
*/
SELECT category,
       COUNT(quantity_per_unit) AS num_products
FROM products 
GROUP BY category
HAVING COUNT(quantity_per_unit) > 10;


/*
Q14
Find suppliers whose average product price exceeds 30.
*/
SELECT s.company, 
       AVG(p.list_price) AS avg_product_price
FROM products p 
INNER JOIN suppliers s 
ON p.supplier_ids = s.id
GROUP BY s.id, s.company
HAVING AVG(p.list_price) > 30;


/*
Q15
Display customers whose total freight exceeds 500.
*/
SELECT c.first_name, 
       c.last_name,
       SUM(o.shipping_fee) AS total_freight
FROM customers c 
INNER JOIN orders o 
ON c.id = o.customer_id
GROUP BY c.id, c.first_name, c.last_name
HAVING SUM(o.shipping_fee) > 500;

/*
Q16
Display each employee and total number of orders handled.
*/
SELECT e.first_name,
       e.last_name,
       COUNT(o.id) AS num_orders
FROM employees e 
INNER JOIN orders o 
ON e.id = o.employee_id 
GROUP BY e.id, e.first_name, e.last_name;


/*
Q17
Display each shipper and number of shipped orders.
*/
SELECT s.company, 
       COUNT(o.shipper_id) AS shipped_orders
FROM shippers s
INNER JOIN orders o 
ON s.id = o.shipper_id
GROUP BY s.company;



/*
Q18
Find countries having more than five customers.
*/
SELECT country_region,
       COUNT(id) AS num_customers
FROM customers
GROUP BY country_region
HAVING COUNT(id) > 5;

/*
Q19
Display categories whose average unit price exceeds 25.
*/
SELECT category,
       AVG(list_price * quantity_per_unit) AS avg_unit_price
FROM products 
GROUP BY category
HAVING AVG(list_price * quantity_per_unit) > 25;

-- CORRECT QUERY
SELECT category,
       AVG(list_price) AS avg_unit_price
FROM products
GROUP BY category
HAVING AVG(list_price) > 25;



/*
Q20
Display products sold more than 20 times.
*/
SELECT p.product_name,
       COUNT(s.id)
FROM products p 
INNER JOIN suppliers s 
ON s.id = p.supplier_ids
GROUP BY p.supplier_ids, p.product_name
HAVING COUNT(p.supplier_ids) > 20;

/*
You wrote

products
JOIN suppliers

But suppliers know nothing about sales.

Sales happen in

orders
order_details

or

order_details_status

depending on schema.

You should first inspect the schema.

For example

order_details
------------
order_id
product_id
quantity
unit_price

Then the query becomes
*/
SELECT p.product_name, 
       SUM(od.quantity) AS total_quantity
FROM products p 
INNER JOIN order_details od
ON p.id = od.product_id
GROUP BY p.id, p.product_name
HAVING SUM(od.quantity) > 20;


/***********************  Round 4 – String Functions ***********************************/

/*
Q26
Display employee initials.
*/
SELECT CONCAT(SUBSTRING(first_name, 1, 1), SUBSTRING(last_name, 1, 1)) AS employee_initials
FROM employees;

/*
Q27
Display customer names in uppercase.
*/
SELECT UPPER(first_name) AS customer_firstname,
       UPPER(last_name) AS customer_lastname
FROM customers;

/*
Q28
Display product names in lowercase.
*/
SELECT LOWER(product_name) AS product_names
FROM products;

/*
Q29
Display first four characters of every category.
*/
SELECT SUBSTRING(Category, 1, 4) AS category_initials
FROM products;

-- ALTERNATIVE WAY
SELECT LEFT(category,4) AS category_initials
FROM products;

/*
Q30
Display supplier names along with name length.
*/
SELECT company,
       LENGTH(company) AS company_length
FROM suppliers;


/*
Q31
Display customer names without spaces using TRIM().
*/
SELECT TRIM(first_name) AS first_name,
       TRIM(last_name) AS last_name
FROM customers;


/*
Q32
Display first three letters of every city.
*/
SELECT SUBSTRING(city, 1, 3) AS city_initials
FROM customers;


/*
Q33
Display full employee names using CONCAT().
*/
SELECT CONCAT(first_name, ' ', last_name) AS full_name
FROM employees;

/*
Q34
Display products whose names start with C.
*/
SELECT *
FROM products
WHERE product_name LIKE 'Northwind Traders C%';


/*
Q35
Display products whose name length exceeds 10.
*/
SELECT *
FROM products 
WHERE LENGTH(product_name) > 10;



/***************************** Round 5 – Mixed Interview Questions *****************************/
/*
Q36
Find the customer who placed the maximum number of orders.
*/
SELECT c.first_name,
       c.last_name,
       COUNT(o.id) AS num_orders
FROM customers c 
INNER JOIN orders o 
ON c.id = o.customer_id
GROUP BY c.id, c.first_name, c.last_name
ORDER BY COUNT(o.id) DESC
LIMIT 1;

/* Here I have one question that if we have orders with same count as MAX should we show both ? */
SELECT c.first_name,
       c.last_name,
       COUNT(o.id) AS total_orders
FROM customers c
JOIN orders o
ON c.id = o.customer_id
GROUP BY c.id, c.first_name, c.last_name
HAVING COUNT(o.id)=(
    SELECT MAX(order_count)
    FROM(
        SELECT COUNT(*) AS order_count
        FROM orders
        GROUP BY customer_id
    ) t
);

/*
Q37
Find the category generating the highest revenue.
*/
SELECT category,
       SUM(list_price) AS net_revenue
FROM products
GROUP BY category
ORDER BY SUM(list_price) DESC
LIMIT 1;

-- CORRECT QUERY
SELECT p.category,
       SUM(od.unit_price * od.quantity) AS revenue
FROM products p
JOIN order_details od
ON p.id=od.product_id
GROUP BY p.category
ORDER BY revenue DESC
LIMIT 1;

/*
Q38
Find the supplier supplying the most products.
*/
SELECT s.company,
       COUNT(p.id) AS num_products
FROM suppliers s 
INNER JOIN products p
ON s.id = p.supplier_ids
GROUP BY s.id, s.company
ORDER BY COUNT(p.id) DESC
LIMIT 1;


/*
Q39
Find the employee who handled the maximum orders.
*/
SELECT e.first_name, 
	   e.last_name,
       COUNT(o.id) AS num_orders
FROM employees e 
INNER JOIN orders o 
ON e.id = o.employee_id
GROUP BY e.id, e.first_name, e.last_name
ORDER BY COUNT(o.id) DESC
LIMIT 1;

/*
Q40
Find the shipper that shipped the most orders.
*/
SELECT s.company,
	   COUNT(o.id) AS num_orders
FROM shippers s 
INNER JOIN orders o 
ON s.id = o.shipper_id
GROUP BY s.id,s.company
ORDER BY COUNT(o.id) DESC
LIMIT 1;
       

/*
Q41
Find the five most expensive products.
*/
SELECT product_name, list_price
FROM products
ORDER BY list_price DESC
LIMIT 5;

/*
Q42
Find customers who ordered products from more than three categories.
*/


/*
Q43
Find suppliers who never supplied any product.
*/
SELECT s.company
FROM suppliers s 
LEFT JOIN products p
ON s.id = p.supplier_ids
WHERE p.id IS NULL;


/*
Q44
Find categories with no products.
*/
SELECT category, COUNT(*) AS num_products
FROM products
GROUP BY category
HAVING COUNT(*) = 0;

/* Requires Category Table defined seperately */
-- CORRECT QUERY
SELECT c.category_name
FROM categories c
LEFT JOIN products p
ON c.id = p.category_id
WHERE p.id IS NULL;

/*
Q45
Display products whose price is greater than the average price of their category.
*/
SELECT product_name, 
       category,
       list_price,
       AVG(list_price)
FROM products
GROUP BY category, product_name, list_price
HAVING list_price > AVG(list_price);

-- CORRECT QUERY
SELECT p1.product_name,
       p1.category,
       p1.list_price
FROM products p1
WHERE p1.list_price >
(
    SELECT AVG(p2.list_price)
    FROM products p2
    WHERE p2.category = p1.category
);


/************************* Round 6 – Dashboard (Interview Favorite) *************************/
/* 
Q46
Create a one-row dashboard showing
Total Customers
Total Employees
Total Suppliers
Total Categories
Total Products
Total Orders
Average Product Price
Highest Product Price
Lowest Product Price
*/
SELECT
(
    SELECT COUNT(*) FROM customers
) AS TotalCustomers,

(
    SELECT COUNT(*) FROM employees
) AS TotalEmployees,

(
    SELECT COUNT(*) FROM suppliers
) AS TotalSuppliers,

(
    SELECT COUNT(DISTINCT category)
    FROM products
) AS TotalCategories,

(
    SELECT COUNT(*)
    FROM products
) AS TotalProducts,

(
    SELECT COUNT(*)
    FROM orders
) AS TotalOrders,

(
    SELECT AVG(list_price)
    FROM products
) AS AverageProductPrice,

(
    SELECT MAX(list_price)
    FROM products
) AS HighestProductPrice,

(
    SELECT MIN(list_price)
    FROM products
) AS LowestProductPrice;

/* 
Q47
Create a country report
Country
Customers
Orders
Total Freight
Average Freight
*/
SELECT c.country_region,
       c.first_name,
	   c.last_name,
       o.id,
       SUM(o.shipping_fee) AS total_freight,
       AVG(o.shipping_fee) AS avg_freight
FROM customers c 
INNER JOIN orders o 
ON c.id = o.customer_id
GROUP BY c.id, c.first_name, c.last_name, c.country_region, o.id;


-- CORRECT QUERY
/*
Your query
GROUP BY customer,id,orderid
Because of grouping by order id, every row becomes one order.
That destroys the aggregation.
*/
SELECT
    c.country_region,
    COUNT(DISTINCT c.id) AS Customers,
    COUNT(o.id) AS Orders,
    SUM(o.shipping_fee) AS TotalFreight,
    AVG(o.shipping_fee) AS AverageFreight
FROM customers c
LEFT JOIN orders o
ON c.id = o.customer_id
GROUP BY c.country_region;


/* 
Q48
Create an employee performance report
Employee
Orders
Total Freight
Average Freight
Sort by Orders DESC.
*/
SELECT e.first_name,
       e.last_name,
       o.id,
       SUM(o.shipping_fee) AS total_freight,
       AVG(o.shipping_fee) AS avg_freight
FROM employees e 
INNER JOIN orders o 
ON e.id = o.employee_id
GROUP BY e.first_name, e.last_name, o.id
ORDER BY o.id DESC;

/*
Your mistake

Grouped by
o.id

That means
one row per order

instead of
one row per employee.
*/
-- CORRECT QUERY
SELECT
    CONCAT(e.first_name,' ',e.last_name) AS Employee,
    COUNT(o.id) AS Orders,
    SUM(o.shipping_fee) AS TotalFreight,
    AVG(o.shipping_fee) AS AverageFreight
FROM employees e
LEFT JOIN orders o
ON e.id=o.employee_id
GROUP BY e.id,e.first_name,e.last_name
ORDER BY Orders DESC;

/* 
Q49
Create a category revenue report
Category
Products
Average Price
Revenue
Sort by Revenue DESC.
*/
SELECT p.category,
	   p.product_name,
       AVG(p.list_price) AS avg_price,
	   SUM(od.unit_price * od.quantity) AS revenue
FROM products p
INNER JOIN order_details od 
ON p.id = od.product_id
GROUP BY p.id, p.product_name, p.category
ORDER BY revenue DESC;

-- CORRECT WAY
/*
Your query

GROUP BY
product

So you're getting
one row per product

instead of
one row per category.

*/
SELECT
    p.category,
    COUNT(DISTINCT p.id) AS Products,
    AVG(p.list_price) AS AveragePrice,
    SUM(od.unit_price * od.quantity * (1-od.discount)) AS Revenue
FROM products p
JOIN order_details od
ON p.id=od.product_id
GROUP BY p.category
ORDER BY Revenue DESC;




/* 
Q50 (Most Common Interview Question)
Create a report showing
Customer
Employee
Category
Supplier
Product
Quantity
UnitPrice
Discount
Revenue
OrderDate
ShipCountry
using the appropriate joins.
*/
SELECT c.first_name AS customer_firstname,
       c.last_name AS customer_lastname,
       e.first_name AS employee_firstname,
       e.last_name AS employee_lastname,
       p.category,
       s.company,
       p.product_name,
       od.quantity,
       od.unit_price,
       od.discount,
       od.unit_price * od.quantity AS revenue,
       o.order_date,
       o.ship_country_region
FROM customers c 
INNER JOIN orders o 
ON c.id = o.customer_id
INNER JOIN employees e
ON e.id = o.employee_id
INNER JOIN order_details  od 
ON od.order_id = o.id
INNER JOIN products p 
ON od.product_id = p.id
INNER JOIN suppliers s
ON s.id=p.supplier_ids;

       

/*CORRECT QUERY*/
SELECT
		CONCAT(c.first_name,' ',c.last_name) AS Customer,
		CONCAT(e.first_name,' ',e.last_name) AS Employee,
		p.category,
		s.company AS Supplier,
		p.product_name,
		od.quantity,
		od.unit_price,
		od.discount,
		od.unit_price*od.quantity*(1-od.discount) AS Revenue,
		o.order_date,
		o.ship_country_region
FROM orders o
JOIN customers c
ON o.customer_id=c.id
JOIN employees e
ON o.employee_id=e.id
JOIN order_details od
ON od.order_id=o.id
JOIN products p
ON od.product_id=p.id
JOIN suppliers s
ON p.supplier_ids=s.id;





