/***************************  Round 1 – GROUP BY + HAVING  *******************************/
/*  
Q 1 Display each country and the number of customers in that country.
*/
SELECT country,
       COUNT(*) AS total_customers 
FROM customers
GROUP BY country;

/*  Q2 Display departments having more than one employee. */
SELECT department, 
       COUNT(*) AS total_employees
FROM employees
GROUP BY department;

-- CORRECT QUERY (forget to filter)
SELECT department, 
       COUNT(*) AS total_employees
FROM employees
GROUP BY department
HAVING COUNT(*) > 1;

/* Q3 Find products whose total sales are greater than 100. */
SELECT product,
       SUM(sales) AS total_sales
FROM products
GROUP BY product
HAVING SUM(sales) > 100; 

-- CORRECT QUERY
SELECT p.product,
       SUM(o.sales) AS total_sales
FROM products p 
INNER JOIN orders o 
ON p.productid = o.productid
GROUP BY p.productid
HAVING SUM(o.sales) > 100;

/* Q4 Display customers who placed more than two orders.  */
SELECT c.firstname,
       c.lastname,
	   COUNT(o.orderid) AS total_orders
FROM customers c
INNER JOIN orders o 
ON c.customerid = o.customerid 
GROUP BY c.customerid
HAVING COUNT(o.orderid) > 2;

/* Q5 Display salespersons who handled at least three orders.  */
SELECT e.firstname,
       e.lastname,
	   COUNT(o.orderid) AS total_orders
FROM employees e 
INNER JOIN orders o 
ON e.employeeid = o.salespersonid
GROUP BY e.employeeid 
HAVING COUNT(o.orderid) >= 3;

/*  Q6 Find categories whose average product price is greater than 20. */
SELECT category,
       AVG(price) AS avg_price
FROM products
GROUP BY category
HAVING AVG(price) > 20;
       

/* Q7 Display customers whose total quantity ordered is greater than 3.  */
SELECT c.firstname,
       c.lastname,
       SUM(o.quantity) AS total_quantity
FROM customers c
INNER JOIN orders o 
ON c.customerid = o.customerid
GROUP BY c.customerid
HAVING SUM(o.quantity) > 3;

/* Q8 Find departments whose average salary is greater than 60,000. */
SELECT department, 
       AVG(salary) AS avg_salary
FROM employees 
GROUP BY department
HAVING AVG(salary) > 60000;

/* Q9 Display products sold more than twice. */
SELECT p.product,
       SUM(o.quantity) AS total_quantity
FROM products p 
INNER JOIN orders o 
ON p.productid = o.productid
GROUP BY p.productid
HAVING SUM(o.quantity) > 2;


/* Q10 Display order statuses having more than three orders. */
SELECT orderstatus, 
       COUNT(*) AS num_orders
FROM orders
GROUP BY orderstatus
HAVING COUNT(*) > 3;

/****************** Round 2 – GROUP BY + JOIN **********************/
/* Q11 Display customer names and their total sales. */
SELECT c.firstname,
       c.lastname,
       SUM(o.sales) AS total_sales
FROM customers c
INNER JOIN orders o 
ON c.customerid = o.customerid
GROUP BY c.customerid;

/* Q12 Display product names and total quantity sold. */
SELECT p.product,
       SUM(o.quantity) AS total_quantity
FROM products p 
INNER JOIN orders o 
ON p.productid = o.productid
GROUP BY p.productid;

/* Q13 Display salesperson names and total revenue generated. */
SELECT e.firstname,
       e.lastname,
       SUM(o.sales) AS total_revenue
FROM employees e 
INNER JOIN orders o 
ON e.employeeid = o.salespersonid
GROUP BY e.employeeid;

/* Q14 Display customer names and average sales. */
SELECT c.firstname,
       c.lastname,
       AVG(o.sales) AS avg_sales
FROM customers c 
INNER JOIN orders o 
ON c.customerid = o.customerid 
GROUP BY c.customerid;

/* Q15 Display each customer along with their highest sale. */
SELECT c.firstname, 
       c.lastname,
	   MAX(o.sales) AS highest_sales
FROM customers c 
INNER JOIN orders o 
ON c.customerid = o.customerid
GROUP BY c.customerid;

/* Q16 Display each product along with its minimum sale. */
SELECT p.product,
       MIN(o.sales) AS min_sales
FROM products p 
INNER JOIN orders o 
ON p.productid = o.productid
GROUP BY p.product;

/* Q17 Display employees and the number of orders they handled. */
SELECT e.firstname,
       e.lastname,
       COUNT(o.orderid) AS num_orders
FROM employees e 
INNER JOIN orders o 
ON e.employeeid = o.salespersonid
GROUP BY e.employeeid;

/* Q18 Display each product category and total revenue. */
SELECT p.category,
       SUM(o.sales) AS total_revenue
FROM products p 
INNER JOIN orders o 
ON p.productid = o.productid
GROUP BY p.category;

/* Q19 Display each country and total sales generated by customers from that country. */
SELECT c.country,
       SUM(o.sales) AS total_sales
FROM customers c 
INNER JOIN orders o 
ON c.customerid = o.customerid
GROUP BY c.country;

/* Q20 Display each salesperson and the highest sale they handled. */
SELECT e.firstname,
       e.lastname,
	   MAX(o.sales) AS highest_sales
FROM employees e 
INNER JOIN orders o 
ON e.employeeid = o.salespersonid
GROUP BY e.employeeid;


/************************ Round 3 – HAVING + JOIN  *******************************/
/* Q21
Display customers whose total sales exceed 100. */
SELECT c.firstname,
       c.lastname,
       SUM(o.sales) AS total_sales
FROM customers c 
INNER JOIN orders o 
ON c.customerid = o.customerid
GROUP BY c.customerid 
HAVING SUM(o.sales) > 100;

/* Q22
Display products whose total quantity sold is greater than 4. */
SELECT p.product,
       SUM(o.quantity) AS total_quantity
FROM products p 
INNER JOIN orders o 
ON p.productid = o.productid
GROUP BY p.productid 
HAVING SUM(o.quantity) > 4;

/* Q23
Display salespersons whose average sales exceed 30. */
SELECT e.firstname,
       e.lastname,
       AVG(o.sales) AS avg_sales
FROM employees e
INNER JOIN orders o 
ON e.employeeid = o.salespersonid
GROUP BY e.employeeid
HAVING AVG(o.sales) > 30;

/* Q24
Display countries having more than one customer. */
SELECT country,
       COUNT(customerid) AS num_customers
FROM customers
GROUP BY country
HAVING COUNT(customerid) > 1;

/* Q25
Display product categories whose total sales exceed 80. */
SELECT p.category,
       SUM(o.sales) AS total_sales
FROM products p 
INNER JOIN orders o 
ON p.productid = o.productid
GROUP BY p.productid
HAVING SUM(o.sales) > 80;

-- CORRECT QUERY
SELECT p.category,
       SUM(o.sales) AS total_sales
FROM products p 
INNER JOIN orders o 
ON p.productid = o.productid
GROUP BY p.category
HAVING SUM(o.sales) > 80;

/* Q26
Display employees who handled more than two orders. */
SELECT e.firstname,
       e.lastname,
	   COUNT(o.orderid) AS num_orders
FROM employees e 
INNER JOIN orders o 
ON e.employeeid = o.salespersonid
GROUP BY e.employeeid
HAVING COUNT(o.orderid) > 2;

/* Q27
Display customers whose highest sale exceeds 50. */
SELECT c.firstname,
       c.lastname,
	   MAX(o.sales) AS highest_sales
FROM customers c
INNER JOIN orders o 
ON c.customerid = o.customerid
GROUP BY c.customerid
HAVING MAX(o.sales) > 50;

/* Q28
Display products whose average quantity sold exceeds 1. */
SELECT p.product,
       AVG(o.quantity) AS avg_quantity
FROM products p 
INNER JOIN orders o 
ON p.productid = o.productid
GROUP BY p.productid
HAVING AVG(o.quantity) > 1;

/* Q29
Display departments whose total salary exceeds 100000. */
SELECT department,
       SUM(salary) AS total_salary
FROM employees 
GROUP BY department
HAVING SUM(salary) > 100000;

/* Q30
Display order statuses whose average sales exceed 25. */
SELECT orderstatus,
       AVG(sales) AS avg_sales
FROM orders
GROUP BY orderstatus
HAVING AVG(sales) > 25;

/*********************  Round 4 – String Functions  ****************************/
/* 
Q31 Display every employee's full name using CONCAT().
*/
SELECT CONCAT(firstname, " " , lastname) AS employee_name
FROM employees;

/* 
Q32
Display all customer names in uppercase.
*/
SELECT UPPER(firstname) AS customer_firstname,
       UPPER(lastname) AS customer_lastname
FROM customers;


/* 
Q33
Display all product names in lowercase.
*/
SELECT LOWER(product) AS product_name
FROM products;


/* 
Q34
Display the length of every employee's first name.
*/
SELECT firstname, 
       LENGTH(firstname) AS len_first_name
FROM employees;


/* 
Q35
Display the first three characters of every product name.
*/
SELECT SUBSTRING(product, 1, 3) AS first_three_characters
FROM products;

/* 
Q36
Display the last two characters of every customer's last name.
*/
SELECT lastname, SUBSTRING(lastname, LENGTH(lastname) - 2 + 1, 2) AS last_two_chracters
FROM customers;


/* 
Q37
Display employee initials (for example, Frank Lee → FL).
*/ 
SELECT CONCAT(SUBSTRING(firstname, 1, 1), SUBSTRING(lastname, 1, 1)) AS employee_initials
FROM employees;

/*
Q38
Display the first five characters of every shipping address.
*/
SELECT SUBSTRING(shipaddress, 1, 5) AS shipping_address_initials
FROM orders;


/*
Q39
Display customer names after removing leading and trailing spaces using TRIM().
(Even though your sample data may not contain spaces, this tests your knowledge.)
*/
SELECT TRIM(firstname) AS customer_firstname,
       TRIM(lastname) AS customer_lastname
FROM customers;

/*
Q40
Display customer full names in lowercase.
*/
SELECT CONCAT(LOWER(firstname), " ", LOWER(lastname)) AS customer_full_name
FROM customers;


/**************** Round 5 – Mixed Interview Questions  *********************/
/* Q41
Display the full name of every customer and the number of orders they placed.
*/
SELECT CONCAT(c.firstname, " ", c.lastname) AS customer_fullname,
	   COUNT(o.orderid) AS num_orders
FROM customers c
INNER JOIN orders o 
ON c.customerid = o.customerid
GROUP BY c.customerid;

/* Q42
Display each product name in uppercase and its total sales.
*/
SELECT UPPER(p.product) AS product_name,
       SUM(o.sales) AS total_sales
FROM products p 
INNER JOIN orders o 
ON p.productid = o.productid
GROUP BY p.productid;

/* Q43
Display customer initials and total sales.
*/
SELECT CONCAT(SUBSTRING(c.firstname, 1, 1), SUBSTRING(c.lastname, 1, 1)) AS customer_initials,
       SUM(o.sales) AS total_sales
FROM customers c 
INNER JOIN orders o 
ON c.customerid = o.customerid
GROUP BY c.customerid;

/* Q44
Display salesperson full names and the number of orders handled.
*/
SELECT CONCAT(e.firstname, " ", e.lastname) AS salesperson_fullname,
       COUNT(o.orderid) AS num_orders
FROM employees e 
INNER JOIN orders o 
ON e.employeeid = o.salespersonid
GROUP BY e.employeeid;

/* Q45
Display the first four characters of each department and employee count.
*/
SELECT LEFT(department, 4) AS department_initial_characters,
	   COUNT(*) AS num_employees
FROM employees
GROUP BY department;

/* Q46
Display customer names whose first name has more than four characters.
*/
SELECT firstname,
       lastname
FROM customers 
WHERE LENGTH(firstname) > 4;

/* Q47
Display products whose name starts with B and total quantity sold.
*/
SELECT p.product,
       COUNT(o.quantity) AS total_quantity
FROM products p 
INNER JOIN orders o 
ON p.productid = o.productid
WHERE p.product LIKE 'B%'
GROUP BY p.product;

-- CORRECT QUERY
SELECT CONCAT(c.firstname, " ", c.lastname) AS customer_fullname,
       c.country,
	   COUNT(o.orderid) AS total_orders,
       SUM(o.sales) AS total_sales,
       AVG(o.sales) AS avg_sales,
       MAX(o.sales) AS highest_sales,
       MIN(o.sales) AS lowest_sales
FROM customers c
INNER JOIN orders o 
ON c.customerid = o.customerid
GROUP BY
c.customerid,
c.firstname,
c.lastname,
c.country
ORDER BY total_sales DESC;



/* Q48
Display countries where the average customer score is greater than 500.
*/
SELECT country,
       AVG(score) AS avg_score
FROM customers
GROUP BY country
HAVING AVG(score) > 500;


/* Q49
Display product names, category, and total revenue sorted by revenue descending.
*/
SELECT p.product,
       p.category,
       SUM(o.sales) AS total_revenue
FROM products p 
INNER JOIN orders o 
ON p.productid = o.productid
GROUP BY p.product, p.category
ORDER BY total_revenue DESC;


/* Q50
Create a report showing:

Customer Full Name
Country
Total Orders
Total Sales
Average Sales
Highest Sale
Lowest Sale

Order the report by Total Sales in descending order.
*/
SELECT CONCAT(c.firstname, " ", c.lastname) AS customer_fullname,
       c.country,
	   COUNT(o.orderid) AS total_orders,
       SUM(o.sales) AS total_sales,
       AVG(o.sales) AS avg_sales,
       MAX(o.sales) AS highest_sales,
       MIN(o.sales) AS lowest_sales
FROM customers c
INNER JOIN orders o 
ON c.customerid = o.customerid
GROUP BY customer_fullname, c.country
ORDER BY total_sales DESC;

-- CORRECT QUERY

SELECT CONCAT(c.firstname, " ", c.lastname) AS customer_fullname,
       c.country,
	   COUNT(o.orderid) AS total_orders,
       SUM(o.sales) AS total_sales,
       AVG(o.sales) AS avg_sales,
       MAX(o.sales) AS highest_sales,
       MIN(o.sales) AS lowest_sales
FROM customers c
INNER JOIN orders o 
ON c.customerid = o.customerid
GROUP BY
c.customerid,
c.firstname,
c.lastname,
c.country
ORDER BY total_sales DESC;


/*******************  Bonus Interview Questions (Very Common)  ***************************/
/* Q51
Display departments having more than one employee and an average salary above 60,000.
*/
SELECT department,
       COUNT(*) AS num_employees,
       AVG(salary) AS avg_salary
FROM employees
GROUP BY department
HAVING COUNT(*) > 1 AND AVG(salary) > 60000;

/* Q52
Display customers whose full name starts with the letter M.
*/
SELECT CONCAT(firstname, " ", lastname) AS full_name
FROM customers
WHERE CONCAT(firstname, " ", lastname) LIKE 'M%';

/* Q53
Display products where the product name length is greater than five.
*/
SELECT product
FROM products
WHERE LENGTH(product) > 5;

/* Q54
Display the customer with the highest total sales.
*/
SELECT c.firstname,
       c.lastname,
       SUM(o.sales) AS total_sales
FROM customers c 
INNER JOIN orders o 
ON o.customerid = c.customerid
GROUP BY c.customerid, c.firstname, c.lastname
ORDER BY total_sales DESC 
LIMIT 1;



/* Q55
Display the salesperson with the maximum number of handled orders.
*/
SELECT e.firstname,
	   e.lastname, 
       COUNT(o.orderid) AS num_orders
FROM employees e 
INNER JOIN orders o 
ON e.employeeid = o.salespersonid
GROUP BY e.employeeid, e.firstname, e.lastname
ORDER BY num_orders DESC
LIMIT 1;


/* Q56
Display the product category generating the highest revenue.
*/
SELECT p.category, MAX(o.sales) AS highest_revenue
FROM products p
INNER JOIN orders o 
ON p.productid = o.productid
GROUP BY p.category;

-- CORRECT QUERY
SELECT p.category,
       SUM(o.sales) AS total_revenue
FROM products p 
INNER JOIN orders o 
ON p.productid = o.productid 
GROUP BY p.category
ORDER BY total_revenue DESC
LIMIT 1;

/* Q57
Display customer names in uppercase along with the total number of orders.
*/
SELECT UPPER(c.firstname) AS customer_firstname,
       UPPER(c.lastname) AS customer_lastname,
       COUNT(o.orderid) AS total_orders
FROM customers c
INNER JOIN orders o
ON c.customerid = o.customerid
GROUP BY c.customerid;

/* Q58
Display employee initials and total salary paid by department.
*/
SELECT CONCAT(SUBSTRING(firstname, 1, 1), SUBSTRING(lastname, 1, 1)) AS employee_initials,
       department,
       SUM(salary) AS total_salary
FROM employees
GROUP BY employee_initials, department;

-- CORRECT QUERY
SELECT CONCAT(SUBSTRING(firstname, 1, 1), SUBSTRING(lastname, 1, 1)) AS employee_initials,
       department,
       SUM(salary) AS total_salary
FROM employees
GROUP BY employeeid, department;

/* Q59
Display each country and the customer having the highest score.
(Attempt this after you've learned more about subqueries or window functions.)
*/
SELECT country, 
       MAX(score) AS highest_score
FROM customers
GROUP BY country;

/* Q60
Create a business summary report showing:

Product Name
Category
Total Orders
Total Quantity Sold
Total Revenue
Average Revenue per Order
Highest Sale
Lowest Sale

Sort by Total Revenue descending.

*/
SELECT p.product,
       p.category,
       COUNT(o.orderid) AS total_orders,
       SUM(o.quantity) AS total_quantity,
       SUM(o.sales) AS total_revenue,
       AVG(o.sales) AS avg_revenue_per_order,
       MAX(o.sales) AS max_sale,
       MIN(o.sales) AS min_sale
FROM orders o 
INNER JOIN products p 
ON o.productid = p.productid
GROUP BY p.productid, p.category, p.product
ORDER BY total_revenue DESC;













